/* ------------------------------------------------------------------------
   REVIGEN FORGE — SINGLE SOURCE OF TRUTH FOR ALL SITE COPY
   ------------------------------------------------------------------------
   Every word on the page comes from this file.

   COPY RULE FOR THIS DESIGN: the reference is near-wordless. Headlines are
   a few words set enormous; everything else is one line. Where an argument
   needs more room it goes inside an accordion or the FAQ, which are closed
   by default — the page looks quiet, the detail is one tap away. If a block
   of prose is creeping past two lines, it belongs in the FAQ instead.

   PROOF RULE: nothing here is invented. Testimonials, client names and
   numbers were supplied by the studio and are used as given. Anything not
   supplied is simply absent — see `metrics` and `testimonials` below.
------------------------------------------------------------------------- */

export const brand = {
  name: 'Revigen Forge',
  tagline: 'Creative growth studio',
} as const;

export const contact = {
  email: 'revigenforge@gmail.com',
  emailSubject: 'Project enquiry — Revigen Forge',
  social: [{ label: 'Instagram', href: 'https://instagram.com/revigenforge' }],
  // One action, everywhere. Swap for a Calendly URL when one exists.
  cta: { label: 'Book a free call', href: '#contact' },
} as const;

export const nav = {
  links: [
    { label: 'About', href: '#about' },
    { label: 'Services', href: '#services' },
    { label: 'Work', href: '#work' },
    { label: 'Pricing', href: '#pricing' },
  ],
} as const;

/* ── 01 HERO ─────────────────────────────────────────────────────────── */

export const hero = {
  tagline: 'We find where your attention leaks — and close it.',
  /** Second person, their symptom. Not a statement about the world. */
  headline: 'The content isn’t the problem.',
  sub: 'You’re posting. It isn’t converting.',
  audience: 'For business owners and creators.',
  /** Quiet proof in the first screen; the full block comes later. */
  proofLine: 'Overdrive · Zenny Studios · +2 brands',
  scrollHint: '(Scroll)',
} as const;

/* ── 02 ABOUT ────────────────────────────────────────────────────────── */

export const about = {
  label: 'About',
  /** Rendered solid, then `rest` dimmed back — the reference's treatment. */
  lead: 'Revigen Forge is a creative growth studio',
  rest: 'that turns attention into revenue for business owners and creators.',
  /** Replaces the reference's stat cards. Our spine, not invented numbers. */
  cards: [
    { n: '01', title: 'Position', body: 'Decide what you’re known for.' },
    { n: '02', title: 'Produce', body: 'Ship weekly without you.' },
    { n: '03', title: 'Convert', body: 'Give attention somewhere to go.' },
  ],
} as const;

/* ── 03 SERVICES ─────────────────────────────────────────────────────── */

export const services = {
  label: 'Services',
  headline: 'What we do',
  aside: '— because posting more is not a strategy.',
  items: [
    {
      n: '01',
      title: 'Positioning',
      line: 'Decide what you’re known for.',
      body: 'The claim you can defend and your competitors cannot copy. Everything downstream is built from it.',
    },
    {
      n: '02',
      title: 'Content systems',
      line: 'Ship weekly without you.',
      body: 'Formats, hooks and a cadence your team can run, so output survives the week you get busy.',
    },
    {
      n: '03',
      title: 'Influencer marketing',
      line: 'Borrow trust you haven’t built yet.',
      body: 'Creator collaborations matched on fit rather than follower count, so the audience you reach is one that buys.',
    },
    {
      n: '04',
      title: 'Production',
      line: 'Video and design, to standard.',
      body: 'Short-form built to survive the first second. Craft is a positioning signal before a word is read.',
    },
    {
      n: '05',
      title: 'Conversion',
      line: 'Turn views into enquiries.',
      body: 'Offers, pages and follow-up. Attention with nowhere to go is an unpaid media company.',
    },
  ],
} as const;

/* ── 04 WORK ─────────────────────────────────────────────────────────── */

export const work = {
  label: 'Our work',
  headline: 'What we’ve made',
  /* Brand plates generated by `node scripts/make-art.mjs` — built from the
     wordmark, since there is no photography yet and stock would undercut a
     studio selling art direction.

     ⚠ REPLACE WITH REAL WORK as soon as clean content stills exist (no
     Instagram UI, no screenshots). Swap the `src` and update `client` and
     `kind`; nothing else needs to change. Set `src: ''` and the frame falls
     back to a labelled placeholder rather than breaking. */
  pieces: [
    { src: './art/plate-dial.png', alt: 'Revigen Forge — attention instrument', client: 'Studio', kind: 'Identity' },
    { src: './art/plate-poster.png', alt: 'Revigen Forge — wordmark poster', client: 'Studio', kind: 'Poster' },
    { src: './art/plate-mark.png', alt: 'Revigen Forge — monogram', client: 'Studio', kind: 'Mark' },
    { src: './art/plate-field.png', alt: 'Revigen Forge — position, produce, convert', client: 'Studio', kind: 'System' },
  ],
  /** Backdrops. Also generated, also replaceable. */
  art: {
    hero: './art/plate-hero.png',
    stack: './art/plate-stack.png',
  },
} as const;

/* ── 05 PROOF ────────────────────────────────────────────────────────── */

export const proof = {
  label: 'Clients',
  headline: 'What they say',
  /** Supplied by the studio. Used verbatim. */
  testimonials: [
    {
      client: 'Overdrive',
      sector: 'Clothing brand',
      quote:
        'Revigen Forge helped us drive strong traffic within hours through targeted UGC collaborations.',
    },
    {
      client: 'Zenny Studios',
      sector: 'Media agency',
      quote:
        'Revigen Forge helped us build a structured foundation for our personal brand and gave our content a much clearer direction.',
    },
    {
      client: 'Brand partner',
      sector: 'Creative brand',
      quote:
        'Revigen Forge brought structure to our creative process and helped us approach content with much more clarity.',
    },
    {
      client: 'Brand partner',
      sector: 'D2C brand',
      quote:
        'They helped us turn our ideas into a clearer creative system and gave our brand a stronger direction.',
    },
  ],

  /* Confirmed by the studio as the Drop 001 reels, measured on Instagram:
     5,140 + 6,148 + 5,777 = 17,065 views against 314 followers.

     The story is reach far exceeding audience size, which is the honest
     way to present modest absolute numbers — and the right one for a
     content studio, since it measures travel rather than vanity. Do not
     round up and do not add figures that were not measured. Set to [] to
     hide the block entirely. */
  metrics: [
    { value: '17,065', label: 'Views across Drop 001' },
    { value: '314', label: 'Followers at the time' },
    { value: '20×', label: 'Reach beyond audience' },
  ],
  metricsNote: 'Overdrive, Drop 001. Three reels, measured on Instagram.',
} as const;

/* ── 06 HOW WE WORK ──────────────────────────────────────────────────── */

export const process = {
  label: 'Process',
  headline: 'How we work',
  aside: 'Four moves. The order is the point.',
  steps: [
    { n: '01', title: 'Diagnose', line: 'Find the leak.' },
    { n: '02', title: 'Position', line: 'Decide the claim.' },
    { n: '03', title: 'Build', line: 'Ship the engine.' },
    { n: '04', title: 'Compound', line: 'Cut what fails.' },
  ],
} as const;

/* ── 07 PRICING ──────────────────────────────────────────────────────── */

export const pricing = {
  label: 'Where to start',
  headline: 'Pick a shape',
  /* No numbers by decision — scope is set on the call. Do not invent tiers
     or prices here; add a `price` field only when one is real. */
  note: 'Priced on scope after the call. No retainer before we both know what the work is.',
  tiers: [
    {
      name: 'Sprint',
      shape: 'Fixed scope · 2–3 weeks',
      pitch: 'Clarity before volume.',
      includes: ['Content and conversion audit', 'Positioning and messaging', 'Direction for the next quarter'],
      featured: false,
    },
    {
      name: 'Engine',
      shape: 'Monthly · rolling',
      pitch: 'The system, running.',
      includes: ['Everything in Sprint', 'Weekly short-form production', 'Editorial calendar and publishing', 'Monthly review'],
      featured: true,
    },
    {
      name: 'Partner',
      shape: 'Embedded · quarterly',
      pitch: 'The whole chain, owned.',
      includes: ['Everything in Engine', 'Influencer and creator programme', 'Offers, funnels and pages', 'Direct access to the team'],
      featured: false,
    },
  ],
} as const;

/* ── 08 FAQ ──────────────────────────────────────────────────────────── */

/* Closed by default. This is where the objection-handling lives, so the
   page can stay near-wordless without leaving objections unanswered. */
export const faq = {
  label: 'FAQ',
  headline: 'Everything you need to know',
  items: [
    {
      q: 'I’ve worked with an agency before and it didn’t work.',
      a: 'Usually because the work started at production instead of positioning. Producing before diagnosing is the most common and most expensive mistake we are asked to undo.',
    },
    {
      q: 'How soon do I see results?',
      a: 'The diagnostic is written in the first weeks and is yours whether or not we continue. Content compounds after that — anyone promising a number without seeing your account is guessing.',
    },
    {
      q: 'Do I need to be on camera?',
      a: 'No. Founder-led content is one format among several. Creator collaborations, product-led and design-led formats all work, and we pick based on what you can sustain.',
    },
    {
      q: 'What if content isn’t actually my problem?',
      a: 'Then we will say so on the first call and point you somewhere better. Most conversion problems turn out to be offer problems wearing a marketing disguise.',
    },
    {
      q: 'What does it cost?',
      a: 'Scope is set after the diagnostic, so you are never quoted before anyone understands the problem. Engagements run as a fixed sprint, a monthly engine, or an embedded partnership.',
    },
  ],
} as const;

/* ── 09 CONTACT ──────────────────────────────────────────────────────── */

export const cta = {
  label: 'Contact',
  headline: 'Let’s find your leak',
  line: 'Tell us what you’re building and where it stalls. Wrong fit? We’ll say so on the first call.',
  marquee: [
    'Positioning',
    'Content systems',
    'Influencer marketing',
    'Production',
    'Conversion',
  ],
} as const;

export const footer = {
  prompt: 'Start with a free call at',
  legal: `© ${new Date().getFullYear()} Revigen Forge`,
} as const;
